name: Run tests on CI

on:
  workflow_dispatch:
  push:

jobs:
  setup-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install python
        run: python --version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the tests
        env:
          OANDA_DEMO_API_KEY: ${{ secrets.OANDA_DEMO_API_KEY }}
        run: behave -v -s -f html -o ./reports/tests_report.html
      - name: Upload test reports to github artifacts
          uses: actions/upload-artifact@v4
          with:
            name: test-reports
            path: ./reports/