name: Run tests on CI

on:
  workflow_dispatch:
  push:

jobs:
  setup-evn:
    runs-on: ubuntu-latest

    steps:
      - name: Setup API access token as env variable
        env:
          DEMO_API_KEY: ${{ secrets.OANDA_DEMO_API_KEY }}
        run: |
          export OANDA_DEMO_API_KEY=env.DEMO_API_KEY
          echo $OANDA_DEMO_API_KEY
